server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /fuzhou-mahjong/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /fuzhou-mahjong/index.html;
    }

    location / {
        return 301 /fuzhou-mahjong/;
    }
}
